lr: 1e-5
init_epoch: 25
epochs: 300
test_epoch: 25
restore: true
gpu_id: 0
is_debug: yes
feat_dim: 2883
name: 'coarse_mvp2m'
save_path: 'results'

train_file_path: 'data/pollen/train_split.txt'
train_data_path: 'data/pollen/train/'
train_image_path: 'data/pollen/train'

test_file_path: 'data/pollen/train_split.txt'
test_data_path: 'data/pollen/train/'
test_image_path: 'data/pollen/train'

coarse_result_file_path: 'data/pollen/train_split.txt'
coarse_result_data_path: 'data/pollen/train'
coarse_result_image_path: 'data/pollen/train'