lr: 1e-4
init_epoch: 0
epochs: 1000
test_epoch: 200
restore: false
batch_size: 16
gpu_id: 0
is_debug: false
feat_dim: 2883
name: 'coarse_mvp2m_2_inputs_none_augmentation'
save_path: 'results'
num_input_images: 2
# Custom modification
view_indices: [0, 1]
train_file_path: 'data/pollen/train_split.txt'
train_data_path: 'data/pollen/train/'
train_image_path: 'data/pollen/train'

test_file_path: 'data/pollen/test_split.txt'
test_data_path: 'data/pollen/test/'
test_image_path: 'data/pollen/test'

coarse_result_file_path: 'data/pollen/train_split.txt'
coarse_result_data_path: 'data/pollen/train'
coarse_result_image_path: 'data/pollen/train'