model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint

  # Put checkpoints under ./checkpoints/<cfg.name>/
  dirpath: "checkpoints/${name}"

  # Use your own name field, then let Lightning fill in checkpoint‐specific fields
  filename: "${name}_epoch{epoch:02d}"

  monitor: "val/loss"
  mode: "min"
  save_top_k: 3
  save_last: true
